[project]
name = "inventory-analysis"
version = "0.1.0"
description = "Various notebooks for inventory analysis."
readme = "README.md"
authors = [
    { name = "Rajdeep Sandhu", email = "168480080+rajdeep-sandhu@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastexcel>=0.20.2",
    "marimo[recommended, lsp]>=0.24.0",
    "matplotlib>=3.11.1",
    "panel>=1.9.3",
]

[project.scripts]
inventory-analysis = "inventory_analysis:main"

[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "lime>=0.2.0.1",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
]
